version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 24
    commands:
      - npm install

  pre_build:
    commands:
      - npm audit --audit-level=high || true

  build:
    commands:
      - npm run build

  post_build:
    commands:
      - aws s3 sync dist/ s3://aws-manoj-portfolio --delete
      - aws cloudfront create-invalidation --distribution-id E2LI2XLSP6KDYE --paths "/*"

artifacts:
  type: NO_ARTIFACTS
